[general]
live_config_reload = true
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
opacity = 0.75

[colors.primary]
# background = "#1e1e2e"
background = "#232136"
# background = "#2a273f"
# background = "#393552"

[font]
normal = {family = "Lilex", style = "Medium"}
italic = {family = "Lilex", style = "Medium Italic"}
bold = {family = "Lilex", style = "Bold"}
bold_italic = {family = "Lilex", style = "Bold Italic"}
size = 11 

[terminal.shell]
# program = "/usr/bin/nu"
# program = "/usr/bin/zsh"
program = "/usr/bin/fish"

[keyboard]
bindings = [{key = "Space", mods = "Control|Alt", mode = "~Search", action = "ToggleViMode"}]
